# Documentation: https://roots.io/trellis/docs/local-development-setup/
wordpress_sites:
  cmua.org:
    site_hosts:
      - cmua.dev
    local_path: site # path targeting local Bedrock site directory (relative to Ansible root)
    site_install: true
    site_title: CMUA Development Site
    admin_user: admin
    # admin_password: (defined in group_vars/development/vault.yml)
    admin_email: timmyintransit@gmail.com
    initial_permalink_structure: /%postname%/ # applied only at time of WP install and when `site_install: true`
    multisite:
      enabled: false
      subdomains: false
    ssl:
      enabled: false
    cache:
      enabled: false
      duration: 30s
    env:
      disable_wp_cron: true
      wp_home: http://cmua.dev
      wp_siteurl: http://cmua.dev/wp
      wp_env: development
      db_name: cmua_dev
      db_user: cmua_dbuser
      # db_password: (defined in group_vars/development/vault.yml)
